name: CI/CD

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Getting the secret MongoDB url
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
