name: Workflows with secret MongoDB URL

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get secret MongoDB url
        uses: actions/checkout@v2
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
